name: Build mkdocs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs-glightbox
          pip install $(mkdocs get-deps)
          
      - name: mkdocs build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs build --clean --strict
